export const SNACKBAR_OPEN = "SNACKBAR_OPEN"
export const SNACKBAR_CLOSE = "SNACKBAR_CLOSE"

export const ASSIGN_DEFAULTS = "ASSIGN_DEFAULTS"

export const LINK_DIALOG_CLOSE = "LINK_DIALOG_CLOSE"
export const LINK_DIALOG_OPEN = "LINK_DIALOG_OPEN"
export const LINK_DIALOG_CHANGE = "LINK_DIALOG_CHANGE"

export const LINK_ADD = "LINK_ADD"
export const LINK_DELETE = "LINK_DELETE"
export const LINK_EDIT = "LINK_EDIT"
export const LINK_COPYURL = "LINK_COPYURL"
export const LINK_SAVE = "LINK_SAVE"

export const FOLDER_SAVE = "FOLDER_SAVE"
export const FOLDER_DELETE = "FOLDER_DELETE"
export const FOLDER_SELECTED = "FOLDER_SELECTED"

export const TOGGLE_DRAWER_DOCK = "TOGGLE_DRAWER_DOCK"
export const TOGGLE_DRAWER_OPEN = "TOGGLE_DRAWER_OPEN"
export const TOGGLE_ADD_OPEN = "TOGGLE_ADD_OPEN"

export const SYNC_CHANGE = "SYNC_CHANGE"
export const LOG_IN_CHANGE = "LOG_IN_CHANGE"
export const OFFLINE = "OFFLINE"
