export const LINK_ADD = "LINK_ADD"
export const LINK_DELETE = "LINK_DELETE"
export const LINK_EDIT = "LINK_EDIT"
export const LINK_COPYURL = "LINK_COPYURL"


export const FOLDER_ADD = "FOLDER_ADD"
export const FOLDER_DELETE = "FOLDER_DELETE"
export const FOLDER_SELECTED = "FOLDER_SELECTED"

export const TOGGLE_DRAWER_DOCK = "TOGGLE_DRAWER_DOCK"
export const TOGGLE_DRAWER_OPEN = "TOGGLE_DRAWER_OPEN"

export const SYNCH_CHANGE = "SYNCH_CHANGE"
export const LOG_IN_CHANGE = "LOG_IN_CHANGE"
export const OFFLINE = "OFFLINE"
